version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=seri
      - POSTGRES_DB=messages
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=seri
      - POSTGRES_DB=messages